export const questions = [
    // verbalReasoning 8
    {
        uqid: `88869484-18c6-11ed-861d-0242ac120002`,
        question: ` Complete con una de las alternativas; uso de conectores.\n_______ de tu abandono, las    noches eran agradables, tiernas   _______ alegres en realidad.`,
        keys: [` Dios - demonio`, `alma - sufriendo`, `amor - Dios`, `alma - corazón `, `llora - ruge`],
        UrlOfImage: null,
        university: `unsch`,
        course: `verbalReasoning`,
        level: 300000,
    }, {
        uqid: `88869484-18c6-11ed-861d-0242ac120002`,
        question: `       Complete con una de las     alternativas; uso de conectores.\n_______ de tu abandono, las noches eran agradables, tiernas _______ alegres en realidad.`,
        keys: [` Dios - demonio`, `alma - sufriendo`, `amor - Dios`, `alma - corazón `, `llora - ruge`],
        UrlOfImage: null,
        university: `unsch`,
        course: `verbalReasoning`,
        level: 300000,
    }, {
        uqid: `1d71253c-18c7-11ed-861d-0242ac120002`,
        question: `  Cuando viajamos a Cocharcas (un distrito que está en la provincia de Chincheros, departamento de Apurimac), nos detuvimos en las alturas de Quri \nAywina porque algunos familiares del marearon. \n En el texto anterior; la relación analógica de causa efecto es:`,
        keys: [`altura(alturas) - mareo (marearon)`, `viaje - Cocharcas`, `distrito - provincia`, `Quri Aywina - puna`, `familiares - mareo`],
        UrlOfImage: null,
        university: `unsch`,
        course: `verbalReasoning`,
        level: 400000,
    }, {
        uqid: `0291c130-18c8-11ed-861d-0242ac120002`,
        question: `Complete la analogía todo - parte \n templo : altar \n universidad :`,
        keys: [ `Quri Aywina - puna`, `familiares - mareo`],
        UrlOfImage: null,
        university: `unsch`,
        course: `verbalReasoning`,
        level: 400000,
    },
    {
        uqid: `7504b394-18c8-11ed-861d-0242ac120002`,
        question: `Las lluvias no son frecuentes en la costa peruana; pero, cuando estas ocurren, causan tremendos destrozos. En los últimos días, hemos visto muchas casas que se caen, calles y parques convertidos en laguna, filtraciones de aguas por los techos de las casas, destrucción de puentes, entre otras desgracias. Es que los pueblos jóvenes no se encuentran preparados, mayormente, para estos acontecimientos. \n ¿Cuál es la idea principal del texto que se debe subrayar?`,
        keys: [`Las lluvias no son frecuentes en la costa peruana; pero, cuando éstas ocurren, causan tremendos destrozos.`, `Las lluvias no son frecuentes en la costa peruana.`, `los pueblos jóvenes no se encuentran preparados, mayormente, para estos acontecimientos.`, `cuando estos ocurren, causan tremendos destrozos.`, `tremendos destrozos.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `verbalReasoning`,
        level: 400000,
    }, {
        uqid: `f28c4818-18c8-11ed-861d-0242ac120002`,
        question: `Tengo el agrado de dirigirme a usted para invitarle a la inauguración del año académico 2017 de la UNSCH, que se llevará a cabo el 17 de abril de 2017, a horas 9 : 00 a.m. en el Paraninfo Universitario. \n Características del párrafo anterior.`,
        keys: [`claridad, orden, cortesía y precisión`, `claridad, orden, brevedad, precisión y cortesía`, `corrección, redundancia, ambigüedad`, `impropiedad, monotonía, precisión y corrección`, `brevedad, ambigüedad, orden y cortesía`],
        UrlOfImage: null,
        university: `unsch`,
        course: `verbalReasoning`,
        level: 400000,
    }, {
        uqid: `47bcb944-18c9-11ed-861d-0242ac120002`,
        question: `¿Cuál es la idea central en el siguiente texto? \n
        Los inventos facilitan la vida del hombre. El teléfono nos permite comunicarnos a grandes distancias en un instante; el ascensor nos facilitó la ascensión y el descenso, evitando la fatiga; los ventiladores nos refrescan en lugares calurosos. En general todo lo creado por la mente humana.`,
        keys: [`Los inventos facilitan la ascensión o el descenso.`, `En general, todo lo creado por la mente humana…`, `Los ventiladores nos refrescan en lugares calurosos.`, `El ascensor nos facilita la ascensión y el descenso, evitando la fatiga.`, `El teléfono nos permite comunicarnos a grandes distancias en un instante.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `verbalReasoning`,
        level: 400000,
    }, {
        uqid: `bf9643c2-18c9-11ed-861d-0242ac120002`,
        question: `Uno de los mayores vicios de la vida escolar es estudiar la $\\underline{víspera}$ de cada examen y presentarse al día siguiente con los ojos irritados por la falta de suelo y la mente sólo aparentemente lúcida.(Guillermo Michel) \n Significado de la palabra subrayada del texto anterior, contextualmente.`,
        keys: [`Una de las horas del oficio divino después de la nona.`, `Día anterior a una fiesta.`, `Dia que antecede inmediatamente a otro determinado(examen).`, `Divisiones del día entre los antiguos romanos.`, `Cosa que antecede a un objeto concreto.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `verbalReasoning`,
        level: 400000,
    },

    // mathematicalReasoning 8
    {
        uqid: `a2e21eea-18d3-11ed-861d-0242ac120002`,
        question: `¿Quién es la hija del hermano de mi padre?`,
        keys: [`prima`, `sobrina`, `tia`, `nieto`, `abuela`],
        UrlOfImage: null,
        university: `unsch`,
        course: `mathematicalReasoning`,
        level: 100000,
    }, {
        uqid: `8d224fac-18d4-11ed-861d-0242ac120002`,
        question: `Indique qué poleas tienen sentido antihorario.`,
        keys: [`$2, 4, 6$`, `$2, 6 $`, `$3, 4, 7$`, `$6, 5, 1$`, `$1, 4, 6$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2FmathematicalReasoning%2F8d224fac-18d4-11ed-861d-0242ac120002.jpg?alt=media&token=5e488c1c-f625-4ee4-8868-be05e3762ebb`,
        university: `unsch`,
        course: `mathematicalReasoning`,
        level: 100000,
    }, {
        uqid: `488b2ce6-18f3-11ed-861d-0242ac120002`,
        question: `Si la proposición ”p” es verdadera, entonces \n \\backsim p \\implies q es:`,
        keys: [`Verdadera.`, `Falsa.`, `Su valor depende de ”q”.`, `Verdadera o Falsa`, `No se pueden determinar.`],
        UrlOfImage: "https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2FmathematicalReasoning%2F8d224fac-18d4-11ed-861d-0242ac120002.jpg?alt=media&token=5e488c1c-f625-4ee4-8868-be05e3762ebb",
        university: `unsch`,
        course: `mathematicalReasoning`,
        level: 1,
    }, {
        uqid: `4e8875cc-18f3-11ed-861d-0242ac120002`,
        question: `Vilma es más vieja que Celina. Nelly, más joven que Celina; pero más vieja que Luz. Esta, a su vez, es más joven que Danna.¿Cuál de las cinco es más joven?`,
        keys: [`Luz`, `Celina`, `Nelly`, `Dnna`, `Vilma`],
        UrlOfImage: null,
        university: `unsch`,
        course: `mathematicalReasoning`,
        level: 1,
    }, {
        uqid: `84b2335e-18f3-11ed-861d-0242ac120002`,
        question: `¿Cuántos puntos de contacto se tendrá en la figura $25$?`,
        keys: [`$975$`, `$600$`, `$625$`, `$1080$`, `$810$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2FmathematicalReasoning%2F2199efee-18d7-11ed-861d-0242ac120002.jpg?alt=media&token=7cd7951b-f865-4962-9f8f-ae601fd93104`,
        university: `unsch`,
        course: `mathematicalReasoning`,
        level: 1,
    }, {
        uqid: `fb5586b4-18f3-11ed-861d-0242ac120002`,
        question: `En la analogía, halle x + y.`,
        keys: [`$22$`, `$18$`, `$20$`, `$23$`, `$24$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2FmathematicalReasoning%2Ffb5586b4-18f3-11ed-861d-0242ac120002.jpg?alt=media&token=3dade4fd-3769-4223-9249-4ce31d04f6d2`,
        university: `unsch`,
        course: `mathematicalReasoning`,
        level: 1,
    }, {
        uqid: `886bbcf8-18f4-11ed-861d-0242ac120002`,
        question: `Efectuar`,
        keys: [`$3/323$`, `$1$`, `$1/19$`, `$19$`, `$8/27$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2FmathematicalReasoning%2F886bbcf8-18f4-11ed-861d-0242ac120002.jpg?alt=media&token=f45e385f-8745-42e6-a904-88e89d84bde5`,
        university: `unsch`,
        course: `mathematicalReasoning`,
        level: 1,
    }, {
        uqid: `13f9984e-18f5-11ed-861d-0242ac120002`,
        question: `Rubén es profesor del cuarto grado de Educación secundaria de la IE ”Mariscal Caceres” y tiene a cargo la sección A. Al aplicar la prueba escrita de Matemática, se obtuvieron los siguientes resultados en la siguiente tabla de frecuencias ¿Cuál es el promedio de notas de la sección A?`,
        keys: [`$12.5 años$`, `$10 años$`, `$10,5 años$`, `$11.5 años$`, `$12 años$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2FmathematicalReasoning%2F13f9984e-18f5-11ed-861d-0242ac120002.jpg?alt=media&token=08ae79e0-c1d1-45a1-8ed0-78b9891bf09b`,
        university: `unsch`,
        course: `mathematicalReasoning`,
        level: 1,
    },
    // algebra 2
    {
        uqid: `e1e78332-18f6-11ed-861d-0242ac120002`,
        question: `Resuelve el siguiente sistema de ecuaciones:`,
        keys: [`$x=\\frac{31}{2} ; y=20$`, `$x=\\frac{5}{2} ; y=3$`, `$x=\\frac{1}{3} ; y=\\frac{2}{3}$`, `$x=2 ; y=5$`, `$x=30 ; y=20$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Falgebra%2Fe1e78332-18f6-11ed-861d-0242ac120002.jpg?alt=media&token=3a83db58-8c52-47ce-aac2-33e754a06e95`,
        university: `unsch`,
        course: `algebra`,
        level: 1,
    },
    {
        uqid: `e1e78332-18f6-11ed-861d-0242ac120002`,
        question: `Simplifique:`,
        keys: [`$9$`, `$4$`, `$3$`, `$8$`, `$6$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Falgebra%2F5332c2b8-18f7-11ed-861d-0242ac120002.jpg?alt=media&token=0fdd6fd7-2523-4127-b6a9-3c98ff3801d0`,
        university: `unsch`,
        course: `algebra`,
        level: 1,
    },
    {
        uqid: `bdf9fc6a-18f7-11ed-861d-0242ac120002`,
        question: ` Halle el dominio de la función: \n\n y= f(x)= \\frac{x+2}{x-3}`,
        keys: [`$R - {3}$`, `$R$`, `$R - {-3}$`, `$R - {2}$`, `$R - {5}$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `algebra`,
        level: 1,
    },

    // arithmetic 3
    {
        uqid: `cef09008-18f5-11ed-861d-0242ac120002`,
        question: `15 estudiantes realizan un viaje cuyos gastos convienen pagar por partes iguales, Al término del viaje, 5 de ellos no pudieron pagar; entonces, cada uno de los restantes tuvo que pagar 26 soles más. ¿Cuánto costó el viaje?`,
        keys: [`$780 soles$`, `$880 soles$`, `$590 soles$`, `$760 soles$`, `$950 soles$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `arithmetic`,
        level: 1,
    }, {
        uqid: `f17656ee-18f5-11ed-861d-0242ac120002`,
        question: `El promedio de la edad de 16 estudiantes varones de una aula es de 12 años y al edad promedio de 14 estudiantes mujeres es 15 años. calcular el promedio de la edad de los estudiantes del aula.`,
        keys: [`$13,4$`, `$12,5$`, `$13,8$`, `$14,5$`, `$12,8$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `arithmetic`,
        level: 1,
    }, {
        uqid: `411bc828-18f6-11ed-861d-0242ac120002`,
        question: `El máximo común divisor de dos números es 8. ¿Cuál es el mínimo común múltiplo de dichos números si su producto es 1344?`,
        keys: [`$168$`, `$180$`, `$188$`, `$208$`, `$104$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `arithmetic`,
        level: 1,
    },


    // trigonometry 1
    {
        uqid: `dce2b908-18f9-11ed-861d-0242ac120002`,
        question: `Convierte 140^{g} a radianes.`,
        keys: [`$\\frac{7}{10}\\pirad$`, `$\\frac{7}{2}\\pirad$`, `$\\frac{9}{10}\\pirad$`, `$\\frac{3}{10}\\pirad$`, `$\\frac{1}{10}\\pirad$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `trigonometry`,
        level: 1,
    }, {
        uqid: `4920f1fc-18fa-11ed-861d-0242ac120002`,
        question: `Determine el valor numérico de \n E=\\frac{4[sen(-30°)]^{2}+13]}{tg(-180°)+sec(-60°)}`,
        keys: [`$7$`, `$6$`, `$8$`, `$9$`, `$10$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `trigonometry`,
        level: 1,
    },
    {
        uqid: `873939d6-18fa-11ed-861d-0242ac120002`,
        question: `De la figura, calcule tg\\theta + ctg(\\theta +8°) sabiendo que EB = 2(CE).`,
        keys: [`$\\frac{7}{4}$`, `$\\frac{4}{7}$`, `$\\frac{4}{3}$`, `$\\frac{3}{4}$`, `$\\frac{1}{3}$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Ftrigonometry%2F873939d6-18fa-11ed-861d-0242ac120002.jpg?alt=media&token=2033026a-422f-44a9-8558-8acdedd91782`,
        university: `unsch`,
        course: `trigonometry`,
        level: 1,
    },

    // geometry 2
    {
        uqid: `0d61c210-18f8-11ed-861d-0242ac120002`,
        question: `De la figura mostrada, los pentágonos ABCDE, PQRST son regulares y semejantes de razón \\frac{6}{8}. Halle el lado del pentágono menor.`,
        keys: [`$6 u$`, `$2 u$`, `$4 u$`, `$5 u$`, `$3 u$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Fgeometry%2F0d61c210-18f8-11ed-861d-0242ac120002.jpg?alt=media&token=893bffe2-5a19-4f17-8800-c0a1cbcb60eb`,
        university: `unsch`,
        course: `geometry`,
        level: 1,
    }, {
        uqid: `bde2d9bc-18f8-11ed-861d-0242ac120002`,
        question: `En un trapecio, la mediana mide 14 cm más que la base menor y esta, la tercera parte de la base mayor. ¿Cuánto mide la base mayor? `,
        keys: [`$42 cm$`, `$28 cm$`, `$84 cm$`, `$14 cm$`, `$58 cm$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `geometry`,
        level: 1,
    }, {
        uqid: `63feaeac-18f9-11ed-861d-0242ac120002`,
        question: `En la figura mostrada, halle FG sabiendo que AB//FG y G es baricentro`,
        keys: [`$10 cm$`, `$15 cm$`, `$14 cm$`, `$25 cm$`, `$20 cm$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Fgeometry%2F63feaeac-18f9-11ed-861d-0242ac120002.jpg?alt=media&token=863d8cab-4290-4657-8c98-31df8d7f354d`,
        university: `unsch`,
        course: `geometry`,
        level: 1,
    },
    // physics 10
    {
        uqid: `3e17a02a-18fb-11ed-861d-0242ac120002`,
        question: ` Determine el valor de x si la ecuación V = h^{x}W es dimensionalmente correcta, donde \n\n W = velocidad angular \n V = velocidad lineal \n h =altura`,
        keys: [`$1$`, `$2$`, `$3$`, `$-1$`, `$-2$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `physics`,
        level: 1,
    },
    {
        uqid: `c670cf64-18fb-11ed-861d-0242ac120002`,
        question: `La gráfica muestra el movimiento variado de un móvil. Halle el espacio total recorrido por el móvil.`,
        keys: [`$34 m$`, `$30 m$`, `$40 m$`, `$20 m$`, `$24 m$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Fphysics%2Fc670cf64-18fb-11ed-861d-0242ac120002.jpg?alt=media&token=3a66a668-dbc0-4f29-8dcf-87146e34a6fe`,
        university: `unsch`,
        course: `physics`,
        level: 1,
    }, {
        uqid: `27cdb51a-18fc-11ed-861d-0242ac120002`,
        question: `Un proyectil se dispara con una velocidad de 36 km/h.¿Qué altura máxima alcanza el proyectil? Asume = 10 m/s^{2}.`,
        keys: [`$3,2 m$`, `$2,8 m$`, `$4,8 m$`, `$5,2 m$`, `$1,8 m$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Fphysics%2F27cdb51a-18fc-11ed-861d-0242ac120002.jpg?alt=media&token=b8f8bf14-47cc-44d1-9f20-36bb0540b098`,
        university: `unsch`,
        course: `physics`,
        level: 1,
    }, {
        uqid: `c93a7ffa-18fc-11ed-861d-0242ac120002`,
        question: `Una rueda gira a razón de 8 rad/s. Calcule la velocidad tangencial del punto A.`,
        keys: [`$24 m/s$`, `$20 m/s$`, `$15 m/s$`, `$10 m/s$`, `$12 m/s$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Fphysics%2Fc93a7ffa-18fc-11ed-861d-0242ac120002.jpg?alt=media&token=773ad1c6-07a4-4f33-bcc5-23271f3bb460`,
        university: `unsch`,
        course: `physics`,
        level: 1,
    }, {
        uqid: `bdd78f6c-18fd-11ed-861d-0242ac120002`,
        question: `Halle el módulo de la fuerza resultante en el sistema de fuerzas.`,
        keys: [`$\\sqrt{26}$`, `$\\sqrt{17}$`, `$\\sqrt{21}$`, `$\\sqrt{11}$`, `$\\sqrt{13}$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Fphysics%2Fbdd78f6c-18fd-11ed-861d-0242ac120002.jpg?alt=media&token=cf82f15f-9ff1-407b-8925-ebaf68660561`,
        university: `unsch`,
        course: `physics`,
        level: 1,
    }, {
        uqid: `451417d4-18fe-11ed-861d-0242ac120002`,
        question: `Un auto se mueve con una rapidez constante de 72 km/h hacia una pared, como se muestra en la figura. ¿En cuánto tiempo llegará a la pared?`,
        keys: [`$15 s$`, `$20 s$`, `$30 s$`, `$25 s$`, `$10 s$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Fphysics%2F451417d4-18fe-11ed-861d-0242ac120002.jpg?alt=media&token=a25ef35c-42e3-413b-a00b-f16ec46c141c`,
        university: `unsch`,
        course: `physics`,
        level: 1,
    }, {
        uqid: `d597d8d6-18fe-11ed-861d-0242ac120002`,
        question: `En la figura mostrada, calcule el peso del bloque P para que el sistema esté en equilibrio. La superficie es lisa.`,
        keys: [`$90 N$`, `$100 N$`, `$80 N$`, `$120 N$`, `$150 N$`],
        UrlOfImage: `https://firebasestorage.googleapis.com/v0/b/gauler-665ba.appspot.com/o/imagesOfBQ%2Fphysics%2Fd597d8d6-18fe-11ed-861d-0242ac120002.jpg?alt=media&token=bdd41bfa-742f-48e0-a897-6f6b9e8aecd2`,
        university: `unsch`,
        course: `physics`,
        level: 1,
    },
    // chemistry 7
    {
        uqid: `00c9e064-1902-11ed-861d-0242ac120002`,
        question: `Dada la siguiente serie de elementos químicos: \n Na, k, Mg, Ca, O, Cl, Te, Hg \n\n  Señale la alternativa que contiene solo metales.`,
        keys: [`k, Mg, Ca, Hg`, `Na, Ca, O, Te`, `k, Mg, Ca, Cl`, `O, Cl, Te, Hg`, `k, Ca, O, Na`],
        UrlOfImage: null,
        university: `unsch`,
        course: `chemistry`,
        level: 1,
    }, {
        uqid: `506ddfd0-1902-11ed-861d-0242ac120002`,
        question: `Señale con \”V\” la proposición verdadera y con \”F\” la falsa e indique la alternativa correcta. \n\n 1. El cloruro de sodio (NaCl) tiene enlace iónico. (  ) \n 2. El agua (H_2O) posee enlace covalente. (  ) \n 3. El cobre (Cu) tiene enlace metálico. (  ) \n 4. El óxido férrico (Fe_2O_2) posee enlace covalente. (  ) \n 5. El ozono (O_2) tiene enlace metálico. (  ).`,
        keys: [`VVVFF`, `VVVVV`, `FVFVF`, `VFVFV`, `FFFVV`],
        UrlOfImage: null,
        university: `unsch`,
        course: `chemistry`,
        level: 1,
    }, {
        uqid: `190122b8-1903-11ed-861d-0242ac120002`,
        question: `¿Cuáles son los coeficientes de la ecuación balanceada de la reacción química de combustión del etanol? \n\n C_2H_5OH_(l) + O_2(g) \\longrightarrow CO_2(g) + H_2O(g)`,
        keys: [`$1, 3, 2, 3$`, `$2, 3, 2, 3$`, `$3, 1, 3, 2$`, `$2, 3, 1, 4$`, `$1, 2, 3, 4$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `chemistry`,
        level: 1,
    }, {
        uqid: `733e311c-1903-11ed-861d-0242ac120002`,
        question: `Determine la masa de gramos de anhídrido carbónico(CO2) que se produce cuando combustiona 898 gramos de propano gaseoso, según la reacción:\n\n(escribir la ecuación) \n\n (masas molares en g/mol C_3H_8 = 44, 0_2 = 32, CO_2 = 44, H_2O = 18)`,
        keys: [`$264 g$`, `$132 g$`, `$150 g$`, `$180 g$`, `$200 g$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `chemistry`,
        level: 1,
    }, {
        uqid: `90b02eb2-1903-11ed-861d-0242ac120002`,
        question: `Un recipiente cerrado contiene 5,0 litros de oxígeno gaseoso a la presión de 2,0 atmósferas. ¿Qué volumen ocupará si se le aumenta la presión de 5,0 atmósferas cuando se mantiene constante la temperatura?`,
        keys: [`$2,0 L$`, `$1,0 L$`, `$3,0 L$`, `$4,0 L$`, `$5,0 L$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `chemistry`,
        level: 1,
    }, {
        uqid: `cabf0c5e-1903-11ed-861d-0242ac120002`,
        question: `Señale las consecuencias del cambio climático.`,
        keys: [`disminución de la superficie cubierta de nieve`, `disminución del nivel de mar`, `disminución de la frecuencia de huracanes`, `aumento del volumen de hielo en el Ártico `, `conservación de la biodiversidad en la biosfera`],
        UrlOfImage: null,
        university: `unsch`,
        course: `chemistry`,
        level: 1,
    }, {
        uqid: `0e93232a-1904-11ed-861d-0242ac120002`,
        question: `Señale el proceso electroquímico que ocurre en la celda galvánica de Daniel (Zn - Cu).`,
        keys: [`En el ánodo, pobre el proceso de oxidación.`, `En el cátodo, se produce el fenómeno de oxidación.`, `En el ánodo, ocurre el proceso de reducción.`, `El flujo de electrones se realiza del cátodo hacia el ánodo.`, `El flujo de iones positivos se produce del ánodo hacia el cátodo.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `chemistry`,
        level: 1,
    },

    // literature 7
    {
        uqid: `496457de-18ce-11ed-861d-0242ac120002`,
        question: `¿Quién escribió la obra dramática en la que Romeo se enamora de Julieta, hija de los Mostesco?`,
        keys: [`William Shakespeare`, `Christopher Marlowe`, `Pierre Comeille`, `John Milton`, `Michael de Montaigne`],
        UrlOfImage: null,
        university: `unsch`,
        course: `literature`,
        level: 200000,
    }, {
        uqid: `7f53be98-18ce-11ed-861d-0242ac120002`,
        question: `¿Quién escribió ”Rimas”, obra de la literatura española?`,
        keys: [`Gustavo Adolfo Bécquer`, `Mariano Melgar`, `Lord Byron`, `Walt Whitman`, `Wolfgang von Goethe`],
        UrlOfImage: null,
        university: `unsch`,
        course: `literature`,
        level: 1,
    }, {
        uqid: `d097e1f8-18ce-11ed-861d-0242ac120002`,
        question: `Señale la alternativa que establece correspondencia entre escritor y obra.`,
        keys: [`Jorge Isaacs : María `, `Rómulo Gallegos : Los ríos profundos`, `José Saramago : El tambor de hojalata`, `Jorge Icaza : Todas las sangres`, `Gabriel García Márquez : La colmena`],
        UrlOfImage: null,
        university: `unsch`,
        course: `literature`,
        level: 300000,
    }, {
        uqid: `ff8d61ea-18ce-11ed-861d-0242ac120002`,
        question: `¿Cuál es el escenario principal de la novela ”Cien años de soledad”, del colombiano Gabriel García?`,
        keys: [`Macondo`, `Comala`, `Calemar`, `Magdalena`, `Rumi`],
        UrlOfImage: null,
        university: `unsch`,
        course: `literature`,
        level: 1,
    }, {
        uqid: `1fb8eb00-18d0-11ed-861d-0242ac120002`,
        question: `Conjunto de narraciones escritas por Ricardo Palma que dan cuenta de episodios ocurridos en Perú y anécdotas de personajes peculiares.`,
        keys: [`Tradiciones peruanas`, `Tradiciones cusqueñas`, `Tradiciones de Huamanga`, `Tradiciones andahuaylinas`, `Tradiciones limeñas`],
        UrlOfImage: null,
        university: `unsch`,
        course: `literature`,
        level: 100000,
    }, {
        uqid: `253f302e-18d1-11ed-861d-0242ac120002`,
        question: `Killac es el escenario principal de _______ escrita por _______`,
        keys: [`Aves sin nido - Clorinda Matto de Turner`, `Warma kuyay - José Maria Arguedas`, `Redoble por Rancas - Manuel Scorza`, `Cuentos andinos - Enrique Lopéz Albújar`, `Los perros hambrientos -  Ciro Alegría`],
        UrlOfImage: null,
        university: `unsch`,
        course: `literature`,
        level: 200000,
    }, {
        uqid: `2da92ada-18d1-11ed-861d-0242ac120002`,
        question: ` ¿Quién es el autor de las novelas ”En octubre no hay milagros” y ”Los inocentes”?`,
        keys: [`Oswaldo Reynoso`, `Julio Ramón Ribeyro`, `Mario Vargas Llosa`, `Alfredo Bryce Echenique`, `Miguel Gutierrez`],
        UrlOfImage: null,
        university: `unsch`,
        course: `literature`,
        level: 100000,
    },

    // language 7
    {
        uqid: `9d0d0e7e-18cb-11ed-861d-0242ac120002`,
        question: `¿En qué se diferencia la comunicación humana y animal?`,
        keys: [`el tipo de código`, `los replantes`, `el canal que se utiliza`, `la complejidad del mensaje`, `la ausencia de signos`],
        UrlOfImage: null,
        university: `unsch`,
        course: `language`,
        level: 200000,
    }, {
        uqid: `02b40d54-18cc-11ed-861d-0242ac120002`,
        question: `En la actualidad, ¿cuál es el elemento de la comunicación que se desarrolla significativamente?`,
        keys: [`canal`, `receptor`, `ruido`, `código`, `emisor`],
        UrlOfImage: null,
        university: `unsch`,
        course: `language`,
        level: 100000,
    }, {
        uqid: `4b622aa4-18cc-11ed-861d-0242ac120002`,
        question: `Marque el par de sustantivos derivados.`,
        keys: [`jardinero, clavelito`, `cajas, panes`, `libros, caballo`, `flores, locura`, `venganza, árboles`],
        UrlOfImage: null,
        university: `unsch`,
        course: `language`,
        level: 100000,
    }, {
        uqid: `efd469c6-18cc-11ed-861d-0242ac120002`,
        question: `Marque la alternativa con pronombres personales.`,
        keys: [`tú, la, lo`, `ti, sí, di`, `la, ese, sí`, `nos, ella, sé`, `mi, té, me`],
        UrlOfImage: null,
        university: `unsch`,
        course: `language`,
        level: 200000,
    }, {
        uqid: `1979413e-18cd-11ed-861d-0242ac120002`,
        question: `¿Cuál es la expresión con un verbo conjugado?`,
        keys: [`Indudablemente, no es para tanto.`, `Poder escucharte, ni ilusión.`, `No hablar en este sitio sagrado.`, `Para terminar, mejor trabajar temprano.`, `Perder el tiempo disponible.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `language`,
        level: 200000,
    }, {
        uqid: `c1c6ee7c-18cd-11ed-861d-0242ac120002`,
        question: ` ¿En cuál de las alternativas se emplea indebidamente el gerundio?`,
        keys: [`Keidy no está preveyendo la desgracia.`, `estoy leyendo el preriódico.`, `Él está creyendo el cuento.`, `Estamos proveyendo los insumos.`, `Están viendo los resultados.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `language`,
        level: 100000,
    }, {
        uqid: `fc518976-18cd-11ed-861d-0242ac120002`,
        question: `Marque la alternativa en la que se emplea la conjunción ”y” de manera correcta.`,
        keys: [`Aquí viven leones y hienas`, `Luis y Ismael son profesores.`, `Él enseña Geografía y Historia.`, `Llegaron padre y hijo.`, `En mi huerto, producen naranjas y higos.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `language`,
        level: 100000,
    },

    // civic 1
    {
        uqid: `56f820a6-19c8-11ed-861d-0242ac120002`,
        question: `¿Cuál es el objetivo de la paternidad y maternidad responsable?`,
        keys: [`Lograr que una pareja madura y consciente decida tener un número de hijos.`, `Lograr que los padres asuman la obligación de educar a sus hijos mayores de edad.`, `Hacer que los padres obliguen a sus descendientes a tener un número máximo de hijos.`, `Educar a los nietos de los hijos menores de edad.`, `Tener hijos sin la debida planificación.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `civic`,
        level: 1,
    }, {
        uqid: `5ab67120-19c8-11ed-861d-0242ac120002`,
        question: `Son libertadores políticos consagrados en la Constitución Política del Estado Peruano, de 1993.`,
        keys: [`elegir y ser elegido`, `opinión, interpelación y trabajo`, `iniciativa empresarial,laboral e intelectual`, `asociación, opinion e informacion`, `reunión e información`],
        UrlOfImage: null,
        university: `unsch`,
        course: `civic`,
        level: 1,
    }, {
        uqid: `5ec4d518-19c8-11ed-861d-0242ac120002`,
        question: `Indique una función del Poder Judicial`,
        keys: [`Administrar justicia en todo el país.`, `Procesar y sentenciar a las personas que cometieron un delito..`, `Emitir normas para controlar la inseguridad ciudadana.`, `Dictar normas de prevención para evitar la delincuencia.`, `Interpelar a los ministros.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `civic`,
        level: 1,
    },

    // universalHistory 5
    {
        uqid: `23fbac8e-1911-11ed-861d-0242ac120002`,
        question: `¿Cuál es la ciencia que estudia e interpreta las inscripciones?`,
        keys: [`epigrafía`, `paleografía`, `historia `, `numismática`, `paleontología`],
        UrlOfImage: null,
        university: `unsch`,
        course: `universalHistory`,
        level: 1,
    }, {
        uqid: `541ab162-1911-11ed-861d-0242ac120002`,
        question: `¿Qué institución política romana tenía por funciones la elección del rey, redactar leyes, controlar la función de magistrados?`,
        keys: [`Senado`, `Magistrados`, `Asambleas`, `Patricidio`, `Cornicio`],
        UrlOfImage: null,
        university: `unsch`,
        course: `universalHistory`,
        level: 1,
    },
    {
        uqid: `8f853a9c-1911-11ed-861d-0242ac120002`,
        question: `¿Qué función tenía el tribunal de la Santa Inquisición?`,
        keys: [`Procesar y sentenciar los delitos contra la fe católica`, `Organizar las cruzadas para recuperar la Tierra Santa.`, `Reconocer la condición de santo a los religiosos.`, `Propiciar la expansión del catolicismo.`, `Eliminar el islamismo.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `universalHistory`,
        level: 1,
    }, {
        uqid: `b388f938-1911-11ed-861d-0242ac120002`,
        question: `Orden religiosa que apoyó a la Iglesia Católica en extender la doctrina d ela contrarreforma.`,
        keys: [`Compañia de Jesus`, `Dominico`, `Agustino`, `Fransciscano`, `Mercedario`],
        UrlOfImage: null,
        university: `unsch`,
        course: `universalHistory`,
        level: 1,
    }, {
        uqid: `e10c6e76-1911-11ed-861d-0242ac120002`,
        question: `¿De qué imperio colonial se han independizado las 13 colonias?`,
        keys: [`inglés`, `francés`, `holandes`, `español`, `ruso`],
        UrlOfImage: null,
        university: `unsch`,
        course: `universalHistory`,
        level: 1,
    },
    // historyOfPeru 7
    {
        uqid: `029e2764-1912-11ed-861d-0242ac120002`,
        question: `Característica del periodo lítico tardío.`,
        keys: [`primeras formas de arte rupestre`, `consumo de maíz`, `cultivo de algodón`, `nicio del urbanismo`, `agricultura de secano`],
        UrlOfImage: null,
        university: `unsch`,
        course: `historyOfPeru`,
        level: 1,
    }, {
        uqid: `52f048aa-1912-11ed-861d-0242ac120002`,
        question: ` La cultura sufrió los efectos del fenómeno de El Niño.`,
        keys: [`Moche`, `Huarpa`, `Chavin`, `Recuay`, `Wari`],
        UrlOfImage: null,
        university: `unsch`,
        course: `historyOfPeru`,
        level: 1,
    }, {
        uqid: `7af5d82e-1912-11ed-861d-0242ac120002`,
        question: ` Grupo social que asimilo con mayor facilidad a la cultura hispana.`,
        keys: [`mestizos`, `negros`, `esclavos`, `indígenas`, `yanaconas`],
        UrlOfImage: null,
        university: `unsch`,
        course: `historyOfPeru`,
        level: 1,
    }, {
        uqid: `9fd13d1e-1912-11ed-861d-0242ac120002`,
        question: ` Reorganizó el ejército y estableció su cuartel general en Pativilca, como parte de la corriente libertadora.`,
        keys: [`Bolívar`, `San Martín`, `Santa Cruz`, `Sucre`, `Gamarra`],
        UrlOfImage: null,
        university: `unsch`,
        course: `historyOfPeru`,
        level: 1,
    }, {
        uqid: `e4f23376-1912-11ed-861d-0242ac120002`,
        question: `Batalla que puso fin a la Confederación Peruana- Bolivariana.`,
        keys: [`Yungay`, `Alto Perú`, `Maynas`, `Paucartambo`, `Chupas`],
        UrlOfImage: null,
        university: `unsch`,
        course: `historyOfPeru`,
        level: 1,
    }, {
        uqid: `01ca46a0-1913-11ed-861d-0242ac120002`,
        question: `Tuvo como objetivo formar un gobierno autónomo y nacionalista.`,
        keys: [`Velasco`, `Ollanta`, `Toledo`, `García`, `Bermudez`],
        UrlOfImage: null,
        university: `unsch`,
        course: `historyOfPeru`,
        level: 1,
    }, {
        uqid: `15f6aa56-1913-11ed-861d-0242ac120002`,
        question: `Década de mayor violencia en la historia nacional.`,
        keys: [`$1980 - 1990$`, `$1930 - 1940$`, `$1960 - 1970$`, `$1990 - 2000$`, `$1970 - 1980$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `historyOfPeru`,
        level: 1,
    },

    // biology 8
    {
        uqid: `888198b0-1904-11ed-861d-0242ac120002`,
        question: ` ¿Cómo se denomina a los procesos de la reacciones de síntesis y descomposición de la materia para obtener energía y realizar las funciones vitales de los seres vivos?`,
        keys: [`metabolismo`, `reproducción`, `adaptabilidad`, `irritabilidad`, `crecimiento y desarrollo`],
        UrlOfImage: null,
        university: `unsch`,
        course: `biology`,
        level: 1,
    }, {
        uqid: `ad27dc56-1904-11ed-861d-0242ac120002`,
        question: `Las proteínas, compuestos fundamentales de todos los seres vivos, son macromoléculas complejas formadas por la unión de moléculas sencillas,¿Cómo se denominan?`,
        keys: [`aminoácidos`, `nucleótidos`, `monosacáridos `, `ácidos grasos `, `glicerol`],
        UrlOfImage: null,
        university: `unsch`,
        course: `biology`,
        level: 1,
    }, {
        uqid: `ca455188-1904-11ed-861d-0242ac120002`,
        question: `¿Cómo se designa al organelo conocido como \”central de energía\”, porque transforma la energía de las moléculas nutritivas (glucosa,lípidos y proteínas en energía útil para el crecimiento, reparación y desarrollo celular)?`,
        keys: [`mitocondria`, `aparato de Golgi`, `reticulo endoplasmatico`, `lisosoma`, `peroxisoma`],
        UrlOfImage: null,
        university: `unsch`,
        course: `biology`,
        level: 1,
    }, {
        uqid: `94c2bb44-1905-11ed-861d-0242ac120002`,
        question: `. En la respiración celular aeróbica, las reacciones del ciclo de krebs solo se produce a través de las mitocondrias y no en el citoplasma. ¿Cuál es el factor determinante?`,
        keys: [`$presencia de O_2$`, `$presencia de CO_2$`, `$ausencia de CO_2$`, `$ausencia de O_2$`, `$presencia de agua$`],
        UrlOfImage: null,
        university: `unsch`,
        course: `biology`,
        level: 1,
    }, {
        uqid: `ea4dacf0-1904-11ed-861d-0242ac120002`,
        question: `Un perro, una trucha o una paloma poseen un eje interno que de dan soporte al cuerpo y a los órganos internos, permitiendo que estos organismos tengan mayor movilidad. ¿Por qué tejido está conformado este eje?`,
        keys: [`óseo`, `muscular`, `adiposo`, `nervioso`, `epitelial`],
        UrlOfImage: null,
        university: `unsch`,
        course: `biology`,
        level: 1,
    }, {
        uqid: `b9717eee-1905-11ed-861d-0242ac120002`,
        question: `¿Cuál es la fase que corresponde cuando cada cromátida se dirige a su respectivo polo de la célula durante la mitosis?`,
        keys: [`anafase`, `metafase`, `telofase`, `profase`, `interfase`],
        UrlOfImage: null,
        university: `unsch`,
        course: `biology`,
        level: 1,
    }, {
        uqid: `161efce8-1906-11ed-861d-0242ac120002`,
        question: `¿Cuál es la vía de transmisión de la tuberculosis pulmonar?`,
        keys: [`inspiración de aire contaminado`, `transfusión de sangre infectada`, `ingestión de alimentos contaminados`, `ingestión de agua contaminada`, `relaciones sexuales con personas infectadas`],
        UrlOfImage: null,
        university: `unsch`,
        course: `biology`,
        level: 1,
    }, {
        uqid: `08217ca6-1906-11ed-861d-0242ac120002`,
        question: `¿Cómo se nombra a las sustancias específicas que producen los glóbulos blancos (linfocitos B), cómo mecanismo de defensa ante la presencia de sustancias genéticamente extrañas al organismo?`,
        keys: [`anticuerpo`, `mucus`, `lágrima`, `saliva`, `antígeno`],
        UrlOfImage: null,
        university: `unsch`,
        course: `biology`,
        level: 1,
    },
    // humanAnatomy 5
    {
        uqid: `46260f94-1910-11ed-861d-0242ac120002`,
        question: `En el aparato digestivo, en qué estructura orgánica se produce la absorción de nutrientes.`,
        keys: [`microvellosidades del intestino delgado`, `tejido conjuntivo elástico del intestino delgado`, `músculo liso del intestino delgado`, `intestino delgado y grueso`, `capa intermedia del intestino delgado`],
        UrlOfImage: null,
        university: `unsch`,
        course: `humanAnatomy`,
        level: 1,
    }, {
        uqid: `6cdb9e60-1910-11ed-861d-0242ac120002`,
        question: `¿Qué enfermedad del sistema cardiovascular se define como correcta?`,
        keys: [`Arteriosclerosis, cuando las paredes arteriales sufren taponamiento de grasa e impiden la circulación normal de la sangre.`, `Várices, cuando las venas superficiales se contraen.`, `Varices, cuando las venas superficiales no se dilatan.`, `Infarto cardíaco, cuando hay flujo sanguíneo hacia los ventrículos.`, `Infarto cardíaco, cuando el flujo sanguíneo no llega a las aurículas.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `humanAnatomy`,
        level: 1,
    }, {
        uqid: `988cd40c-1910-11ed-861d-0242ac120002`,
        question: `Estructura específica renal donde se forma la orina.`,
        keys: [`nefrón`, `médula`, `corteza`, `pelvis`, `envoltura`],
        UrlOfImage: null,
        university: `unsch`,
        course: `humanAnatomy`,
        level: 1,
    }, {
        uqid: `b68e9f58-1910-11ed-861d-0242ac120002`,
        question: `¿Cuál es la diferencia entre el acto reflejo y el acto voluntario?`,
        keys: [`El reflejo tiene respuestas rápidas y el voluntario, lentas.`, `El voluntario tiene respuestas rápidas y el reflejo, lentas.`, `El voluntario tiene respuestas diversas y el reflejo , lentas`, `El reflejo se realiza en la protuberancia y el voluntario, en el cerebro`, `El voluntario se produce en el cerebelo y el reflejo, en la médula espinal.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `humanAnatomy`,
        level: 1,
    }, {
        uqid: `e047083a-1910-11ed-861d-0242ac120002`,
        question: `Enfermedad del sistema endocrino donde, por ausencia o malformación de la glándula tiroidea, se generan graves retardos físicos y mentales en las personas.`,
        keys: [`cretinismo`, `gigantismo y enanismo`, `hipotiroidismo`, `hipertiroidismo`, `diabetes mellitus`],
        UrlOfImage: null,
        university: `unsch`,
        course: `humanAnatomy`,
        level: 1,
    },
    // geography 2

    {
        uqid: `6e904e06-19c7-11ed-861d-0242ac120002`,
        question: `En qué región está localizada la Reserva Nacional de Tambopata.`,
        keys: [`Madre de Dios`, `Apurimac`, `Cuzco`, `San Martin`, `Puno`],
        UrlOfImage: null,
        university: `unsch`,
        course: `geography`,
        level: 1,
    }, {
        uqid: `a8e2cb60-19c7-11ed-861d-0242ac120002`,
        question: `¿En qué cuenca hidrográfica se localiza la actual ciudad de Huamanga?`,
        keys: [`Huarpa `, `Pampas`, `Torobamba`, `Qaracha`, `Chichas y Soras`],
        UrlOfImage: null,
        university: `unsch`,
        course: `geography`,
        level: 1,
    }, {
        uqid: `c5d743ae-19c7-11ed-861d-0242ac120002`,
        question: `Qué logró expandir el Perú durante el gobierno del Dr. Jose Luis Bustamante y Rivero.`,
        keys: [`las 200 millas del mar peruano`, `La Antártida`, `la selva amazónica`, `el lago Titicaca`, `las fronteras hacia Bolivia`],
        UrlOfImage: null,
        university: `unsch`,
        course: `geography`,
        level: 1,
    }, {
        uqid: `e70e5094-19c7-11ed-861d-0242ac120002`,
        question: `Cuál es el hábitat del paiche`,
        keys: [`ríos amazónicos`, `lagunas alto-andinas`, `ríos interandinos`, `mar peruano`, `rios de la costa`],
        UrlOfImage: null,
        university: `unsch`,
        course: `geography`,
        level: 1,
    }, {
        uqid: `eb4867bc-19c7-11ed-861d-0242ac120002`,
        question: `En los últimos años el Perú, en qué región se intensificó la explotación ilegal del oro aluvial.`,
        keys: [`Madre de Dios`, `Lima`, `Piura`, `Ayacucho`, `Cajamarca`],
        UrlOfImage: null,
        university: `unsch`,
        course: `geography`,
        level: 1,
    },
    // economy 4
    {
        uqid: `48a3c43e-1913-11ed-861d-0242ac120002`,
        question: `Cual de las siguientes alternativas completa adecuadamente el enunciado.\”Una empresa está constituida por _______ como por _______ que trabajan en ella\”:`,
        keys: [`accionista . empleados`, `dueños - empleados`, `dueños - obreros`, `empresario - empleados`, `socios - trabajadores`],
        UrlOfImage: null,
        university: `unsch`,
        course: `economy`,
        level: 1,
    }, {
        uqid: `80820e74-1913-11ed-861d-0242ac120002`,
        question: `Cual de las siguientes afirmaciones no es atribución del Banco Central de Reserva(BCR)`,
        keys: [`Otorgar créditos a las empresas.`, `Regular la cantidad de dinero de la economía.`, `Administrar las reservas internacionales del país.`, `Emitir billetes y monedas.`, `Informar a la ciudadanía sobre las finanzas nacionales.`],
        UrlOfImage: null,
        university: `unsch`,
        course: `economy`,
        level: 1,
    },
    {
        uqid: `a5eb1192-1913-11ed-861d-0242ac120002`,
        question: `Como se denomina al aumento rápido , generalizado y sostenido de los precios.`,
        keys: [`proceso inflacionario`, `crisis económica`, `devaluación`, `índice de precios al consumidor `, `proceso deflacionario`],
        UrlOfImage: null,
        university: `unsch`,
        course: `economy`,
        level: 1,
    }, {
        uqid: `c5037de4-1913-11ed-861d-0242ac120002`,
        question: `Quién es el responsable de las labores destinadas a recaudar los tributos y hacer cumplir las normas de carácter tributario.`,
        keys: [`Superintendencia Nacional de Administración tributaria`, `Ministerio de Economía y Finanzas`, `Banco Central de Reserva del Perú`, `Instituto Nacional de Administración Tributaria.`, `Banco de Crédito del Perú`],
        UrlOfImage: null,
        university: `unsch`,
        course: `economy`,
        level: 1,
    },
    // topicality 7
    {
        uqid: `ed7ac920-19c8-11ed-861d-0242ac120002`,
        question: `País asiatico que viene desarrollando experimentos militares con armas no convencionales en la cuenca del Pacífico de manera reiterativa.`,
        keys: [`Corea del Norte`, `Filipinas`, `Japón`, `Corea del Sur`, `China`],
        UrlOfImage: null,
        university: `unsch`,
        course: `topicality`,
        level: 1,
    }, {
        uqid: `f1260d46-19c8-11ed-861d-0242ac120002`,
        question: `El llamado \”Río Hablador\” a qué carretera viene afectando e interrumpiendo en estas últimas semanas.`,
        keys: [`Central`, `Panamericana Norte`, `Panamericana Sur`, `Transoceanica`, `Marginal`],
        UrlOfImage: null,
        university: `unsch`,
        course: `topicality`,
        level: 1,
    }, {
        uqid: `f4f99c12-19c8-11ed-861d-0242ac120002`,
        question: `Cuál es la institución encargada de aprobar el Presupuesto General de la República.`,
        keys: [`Congreso de la República`, `Ministerio de Economía y Finanzas`, `Contraloría General de la República`, `Direccion General de Presupuesto Público`, `Poder Ejecutivo`],
        UrlOfImage: null,
        university: `unsch`,
        course: `topicality`,
        level: 1,
    }, {
        uqid: `f9578c9c-19c8-11ed-861d-0242ac120002`,
        question: `A Quien se considera como el creador de Facebook`,
        keys: [`Mark Zuckerberg`, `Louis Braile`, `Henry Cole`, `Edward Jenner`, `Isaac Newton`],
        UrlOfImage: null,
        university: `unsch`,
        course: `topicality`,
        level: 1,
    }, {
        uqid: `fcda4b16-19c8-11ed-861d-0242ac120002`,
        question: `Organismo recientemente creado por el gobierno para hacer frente a los desastres naturales en todo el país `,
        keys: [`COEN`, `SEDAPAL`, `OSIPTEL`, `SENAMHI`, `SEDA`],
        UrlOfImage: null,
        university: `unsch`,
        course: `topicality`,
        level: 1,
    }, {
        uqid: `00e8b954-19c9-11ed-861d-0242ac120002`,
        question: `Triple campeón mundial del boxeo de los pesos pesados fallecido el año 2016.`,
        keys: [`Mohamed Ali`, `George Foreman`, `Oscar \”Ringo\” Bonavena`, `Kent Norton`, `Mauro Mina`],
        UrlOfImage: null,
        university: `unsch`,
        course: `topicality`,
        level: 1,
    }, {
        uqid: `0478c500-19c9-11ed-861d-0242ac120002`,
        question: `Es autor de la obra literaria \”La interpretación de los sueños\”.`,
        keys: [`Sigmund Freud`, `Toni Morrison`, `Nathanael West`, `Ralph Ellison`, `Alice Walter`],
        UrlOfImage: null,
        university: `unsch`,
        course: `topicality`,
        level: 1,
    },

]